[package]
name = "spire_tween"
version = "0.1.2"
authors = ["Houtamelo"]
edition = "2021"
description = "A Slimy tweener library for Godot(4.2+), inspired on the design of DoTween(3rd party package for Unity)"
license = "MIT"
repository = "https://github.com/Houtamelo/spire_tween"
categories = ["game-development", "api-bindings"]
keywords = ["godot", "tweening", "animation", "gdextension", "spire"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
godot = "0.1"
keyframe = "1.1.1"
keyframe_derive = "1.0.0"
uuid = { version = "1.9", features = ["v4"] }
anyhow = "1.0"